---
## Super Linter GitHub Actions ##
name: Prettify Then Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#


# - - - - - - - - - - - - - - - - - - - - - - - - 

# Start the job on all push #
on:
  push:
    branches: [master, main]
    # in case you want to ignore branch
    # branches-ignore: [dev]
  pull_request:
    branches: [master, main]


# - - - - - - - - - - - - - - - - - - - - - - - - 

# jobs:
#   Build:
#     uses: buildteam/.github/workflows/build.yaml@main
#     with:
#       build: gradle

# Set the Job #
jobs:
  Build:
    uses: buildteam/.github/workflows/build.yaml@main
    with:
      build: gradle

  pretty_lint:
    name: Prettify and Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          
      # ~  ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    

      # Run Prettier against code base #
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
     
      # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~


      # Run Linter against code base #
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
      
  # ansible_deploy:
  #   uses: buildteam/.github/workflows/build.yaml@main
  #   with:
  #     build: gradle
    # uses: buildteam/.github/workflows/build.yaml@main
    # - name: Run Ansible playbook
      # uses: dawidd6/action-ansible-playbook@v2.5.0

    # uses: dawidd6/action-ansible-playbook@v2
    # with:
      # build: gradle

  

  # ansible_deploy:
  #   - name: Deplpoy by ansible playbook deploy.yml
  #     uses: dawidd6/action-ansible-playbook@v2
  #     with:
  #       playbook: deploy ansible 
  
  #       directory: ./

  #       inventory: |
  #         [all]
  #         techhive-ubuntu-2 ansible_host=15.188.3.194

  

    


